<?php

declare(strict_types=1);

namespace SlamCsFixer;

use PhpCsFixer\Config as PhpCsFixerConfig;
use PhpCsFixer\Fixer as MainFixer;

final class Config extends PhpCsFixerConfig
{
    public function __construct(bool $version2 = true)
    {
        parent::__construct(sprintf('%s:%s', __NAMESPACE__, $version2 ? 2 : 1));

        $this->setRiskyAllowed(true);
        $this->registerCustomFixers(array(
            new FinalAbstractPublicFixer(),
            new FinalInternalClassFixer(),
            new FunctionReferenceSpaceFixer(),
            new InlineCommentSpacerFixer(),
            new PhpFileOnlyProxyFixer(new MainFixer\Basic\BracesFixer()),
            new PhpFileOnlyProxyFixer(new MainFixer\Semicolon\SemicolonAfterInstructionFixer()),
            new PhpFileOnlyProxyFixer(new MainFixer\Semicolon\SpaceAfterSemicolonFixer()),
            new PhpFileOnlyProxyFixer(new MainFixer\Strict\DeclareStrictTypesFixer()),
            new Utf8Fixer(),
        ));
        $this->setRules(array(
            'Slam/final_abstract_public' => $version2,
            'Slam/final_internal_class' => $version2,
            'Slam/function_reference_space' => true,
            'Slam/inline_comment_spacer' => true,
            'Slam/php_only_braces' => true,
            'Slam/php_only_declare_strict_types' => $version2,
            'Slam/php_only_semicolon_after_instruction' => true,
            'Slam/php_only_space_after_semicolon' => true,
            'Slam/utf8' => $version2,
            'align_multiline_comment' => array(
                'comment_type' => 'all_multiline',
            ),
            'array_syntax' => array(
                'syntax' => 'long',
            ),
            'binary_operator_spaces' => false,
            'blank_line_after_namespace' => true,
            'blank_line_after_opening_tag' => true,
            'blank_line_before_return' => false,
            'blank_line_before_statement' => true,
            'braces' => false,
            'cast_spaces' => true,
            'class_definition' => array(
                'singleItemSingleLine' => true,
            ),
            'class_keyword_remove' => false,
            'combine_consecutive_issets' => false,
            'combine_consecutive_unsets' => false,
            'concat_space' => array(
                'spacing' => 'one',
            ),
            'declare_equal_normalize' => true,
            'declare_strict_types' => false,
            'dir_constant' => true,
            'doctrine_annotation_array_assignment' => true,
            'doctrine_annotation_braces' => true,
            'doctrine_annotation_indentation' => true,
            'doctrine_annotation_spaces' => true,
            'elseif' => true,
            'encoding' => $version2,
            'ereg_to_preg' => true,
            'full_opening_tag' => true,
            'function_declaration' => true,
            'function_to_constant' => true,
            'function_typehint_space' => true,
            'general_phpdoc_annotation_remove' => false,
            'hash_to_slash_comment' => false,
            'header_comment' => false,
            'heredoc_to_nowdoc' => true,
            'include' => true,
            'indentation_type' => true,
            'is_null' => true,
            'line_ending' => true,
            'linebreak_after_opening_tag' => true,
            'list_syntax' => true,
            'lowercase_cast' => true,
            'lowercase_constants' => true,
            'lowercase_keywords' => true,
            'magic_constant_casing' => true,
            'mb_str_functions' => $version2,
            'method_argument_space' => array(
                'keep_multiple_spaces_after_comma' => true,
            ),
            'method_separation' => true,
            'modernize_types_casting' => true,
            'native_function_casing' => true,
            'native_function_invocation' => false,
            'new_with_braces' => true,
            'no_alias_functions' => true,
            'no_blank_lines_after_class_opening' => true,
            'no_blank_lines_after_phpdoc' => true,
            'no_blank_lines_before_namespace' => false,
            'no_break_comment' => true,
            'no_closing_tag' => true,
            'no_empty_comment' => true,
            'no_empty_phpdoc' => true,
            'no_empty_statement' => true,
            'no_extra_consecutive_blank_lines' => array(
                'break',
                'continue',
                'extra',
                'return',
                'throw',
                'use',
                'useTrait',
                'curly_brace_block',
                'parenthesis_brace_block',
                'square_brace_block',
            ),
            'no_homoglyph_names' => true,
            'no_leading_import_slash' => true,
            'no_leading_namespace_whitespace' => true,
            'no_mixed_echo_print' => array(
                'use' => 'echo',
            ),
            'no_multiline_whitespace_around_double_arrow' => false,
            'no_multiline_whitespace_before_semicolons' => false,
            'no_null_property_initialization' => true,
            'no_php4_constructor' => true,
            'no_short_bool_cast' => true,
            'no_short_echo_tag' => true,
            'no_singleline_whitespace_before_semicolons' => true,
            'no_spaces_after_function_name' => true,
            'no_spaces_around_offset' => true,
            'no_spaces_inside_parenthesis' => true,
            'no_superfluous_elseif' => true,
            'no_trailing_comma_in_list_call' => true,
            'no_trailing_comma_in_singleline_array' => true,
            'no_trailing_whitespace' => true,
            'no_trailing_whitespace_in_comment' => true,
            'no_unneeded_control_parentheses' => $version2,
            'no_unneeded_curly_braces' => true,
            'no_unneeded_final_method' => true,
            'no_unreachable_default_argument_value' => true,
            'no_unused_imports' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
            'no_whitespace_before_comma_in_array' => true,
            'no_whitespace_in_blank_line' => true,
            'non_printable_character' => true,
            'normalize_index_brace' => true,
            'not_operator_with_space' => false,
            'not_operator_with_successor_space' => true,
            'object_operator_without_whitespace' => true,
            'ordered_class_elements' => array(
                'use_trait',
                'constant',
                'property',
                'construct',
                'destruct',
                'magic',
                'phpunit',
                'method',
            ),
            'ordered_imports' => true,
            'php_unit_construct' => true,
            'php_unit_dedicate_assert' => true,
            'php_unit_fqcn_annotation' => true,
            'php_unit_strict' => false,
            'php_unit_test_class_requires_covers' => false,
            'phpdoc_add_missing_param_annotation' => false,
            'phpdoc_align' => true,
            'phpdoc_annotation_without_dot' => true,
            'phpdoc_indent' => true,
            'phpdoc_inline_tag' => true,
            'phpdoc_no_access' => true,
            'phpdoc_no_alias_tag' => true,
            'phpdoc_no_empty_return' => true,
            'phpdoc_no_package' => true,
            'phpdoc_no_useless_inheritdoc' => true,
            'phpdoc_order' => true,
            'phpdoc_return_self_reference' => true,
            'phpdoc_scalar' => true,
            'phpdoc_separation' => true,
            'phpdoc_single_line_var_spacing' => true,
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => true,
            'phpdoc_trim' => true,
            'phpdoc_types' => true,
            'phpdoc_types_order' => true,
            'phpdoc_var_without_name' => true,
            'pow_to_exponentiation' => false,
            'pre_increment' => true,
            'protected_to_private' => true,
            'psr0' => true,
            'psr4' => true,
            'random_api_migration' => true,
            'return_type_declaration' => true,
            'self_accessor' => true,
            'semicolon_after_instruction' => true,
            'short_scalar_cast' => true,
            'silenced_deprecation_error' => false,
            'simplified_null_return' => true,
            'single_blank_line_at_eof' => true,
            'single_blank_line_before_namespace' => true,
            'single_class_element_per_statement' => true,
            'single_import_per_statement' => true,
            'single_line_after_imports' => true,
            'single_line_comment_style' => true,
            'single_quote' => true,
            'space_after_semicolon' => true,
            'standardize_not_equals' => true,
            'strict_comparison' => $version2,
            'strict_param' => $version2,
            'switch_case_semicolon_to_colon' => true,
            'switch_case_space' => true,
            'ternary_operator_spaces' => true,
            'ternary_to_null_coalescing' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'unary_operator_spaces' => false,
            'visibility_required' => true,
            'void_return' => true,
            'whitespace_after_comma_in_array' => true,
            'yoda_style' => false,
        ));
    }
}
