name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"
      - "renovate/*"

env:
  INI_VALUES: zend.assertions=1,error_reporting=-1

jobs:
  composer-json-lint:
    name: "Lint composer.json"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
          tools: composer-normalize,composer-require-checker,composer-unused
      - uses: "ramsey/composer-install@v2"

      - run: "composer validate --strict"
      - run: "composer-normalize --dry-run"
      - run: "composer-require-checker check"
      - run: "composer-unused"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.4"
        code-coverage:
          - "none"
        include:
          - php-version: "8.3"
            code-coverage: "pcov"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "${{ matrix.code-coverage }}"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - run: "vendor/bin/phpunit --no-coverage --no-logging"
        if: ${{ matrix.code-coverage == 'none' }}
        timeout-minutes: 3

      - run: "vendor/bin/phpunit --no-logging"
        if: ${{ matrix.code-coverage != 'none' }}
        timeout-minutes: 3

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - run: "vendor/bin/php-cs-fixer fix --verbose --dry-run --diff"

  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - run: "vendor/bin/phpstan analyse --no-progress --error-format=github"
